# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\wxll\car doip\5G\20201118a.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 455)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("niao.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.head_message = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.head_message.setFont(font)
        self.head_message.setObjectName("head_message")
        self.start_btn = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout.addWidget(self.splitter_2)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.middle_message = QtWidgets.QTextEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.middle_message.setFont(font)
        self.middle_message.setReadOnly(True)
        self.middle_message.setObjectName("middle_message")
        self.log_table = QtWidgets.QTabWidget(self.splitter)
        self.log_table.setMinimumSize(QtCore.QSize(722, 286))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.log_table.setFont(font)
        self.log_table.setObjectName("log_table")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.message = QtWidgets.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.message.setFont(font)
        self.message.setReadOnly(True)
        self.message.setObjectName("message")
        self.gridLayout_2.addWidget(self.message, 0, 0, 1, 1)
        self.log_table.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout.setObjectName("gridLayout")
        self.history_table = QtWidgets.QTableWidget(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.history_table.setFont(font)
        self.history_table.setObjectName("history_table")
        self.history_table.setColumnCount(0)
        self.history_table.setRowCount(0)
        self.gridLayout.addWidget(self.history_table, 0, 0, 1, 1)
        self.log_table.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.splitter)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.log_table.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "远程诊断"))
        self.start_btn.setText(_translate("MainWindow", "开始"))
        self.log_table.setTabText(self.log_table.indexOf(self.tab), _translate("MainWindow", "通信报文"))
        self.log_table.setTabText(self.log_table.indexOf(self.tab_4), _translate("MainWindow", "历史信息"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

